sudo: required
dist: trusty
language: cpp
os:
- linux
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
script:
- "./package.sh"
before_deploy:
- export RELEASE_FILE=bin.tar.gz
- ls
- echo "Deploying $RELEASE_FILE to GitHub"
deploy:
  provider: releases
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    repo: Malfoy/BGREAT2
    overwrite: true
  api-key:
    secure: L82QsHtHLSDcmrC77RoNmyJhnpR30YhSnSjSSOMQavPy820i5zEvkiJKyMk/rfbnsXyguCHvAUNu3dQPsuqDOJkPrVWah1JZ/LRmDncfK99UsGU+unppEXqVa0/4l3vBBnEhfcSG7XwRfU4FIilsTFS4dK5Flfi+ex8k8n4dre6xcpux3zwD1wCR3IbXM0cpIF76/v/vxjtxxrkZngGXyuAQbognjWcsnIw36uXXTcIa7uL85xJlEpXNmuJiFzq6oGfNkuWUQdpEI/pkkm0+fklN/dFBVkqSuNedXatq06RBssGKsT1XF8UBK8cjY/OomgyAAhhXX2tam2vSf+9TALPOdR05JZn5PMpkRHOTsPLTqilHfcAnc4DE7+5VdH+NWyrJD+GmMyttud66FfUYqLA/pVkLRYuD34Wova/AttbfOmKEOTPeQjwbOGPvdJ3PWN5coZ2aL2OJjZOBv7+ouQCXL4aAdIRMDYjQssMrISjGTaheD1XKdPUgnEOWLhvIVfabE5T5KMl608AmTUvharQ9NoH5ceZd9Vn2Jnyfo7PUaPEcG+dXS+Ir1QYd/tbrU1oZNIVxha4p/1fbA0oeXdPYF2kL6kaH5y6LQ4P+MFwUZ3DDG5aOnThuZqJQ1IGSI8iJqLQjMWyHZyKfOBDuqsdDTYu+EdNwFdznEwEhaKg=
